greetings:
    path: /v1/greetings/{name}
    methods: [GET]
    controller: App\Infrastructure\Controller\Greetings

_health:
    path: /
    methods: [GET]
    controller: App\Infrastructure\Controller\Health
