# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Controller\Documentation:
        public: true
        arguments:
            $rootDir: '%kernel.project_dir%'

    App\Infrastructure\Cli\GenerateThumbnailCommand:
        public: true
        arguments:
            $rootDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command', command: 'app:generate-thumbnail' }

    App\Infrastructure\Services\ImagineThumbnailGenerator:
        public: true
        arguments:
            - '@Imagine\Imagick\Imagine'
    
    App\Infrastructure\Repository\S3BucketThumbnailRepository:
        public: true
        arguments:
            - '@Aws\S3\S3Client'
            - '%env(string:AWS_THUMBNAIL_BUCKET)%'

    App\Infrastructure\Repository\InMemoryThumbnailRepository:
        public: true

    App\Application\Repository\ThumbnailRepository: '@App\Infrastructure\Repository\S3BucketThumbnailRepository'

    Imagine\Imagick\Imagine:
        public: true

    Aws\S3\S3Client:
        public: true
        arguments:
            - { region: '%env(string:AWS_REGION)%', version: 'latest', credentials: { key: '%env(string:AWS_ACCESS_KEY_ID)%', secret: '%env(string:AWS_SECRET_ACCESS_KEY)%' } }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

when@test:
    services:
        App\Application\Repository\ThumbnailRepository: '@App\Infrastructure\Repository\InMemoryThumbnailRepository'
