apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: letsencrypt
    namespace: thumbnail-generator
spec:
    acme:
        # The ACME server URL prod: https://acme-v02.api.letsencrypt.org/directory staging: https://acme-staging-v02.api.letsencrypt.org/directory
        server: https://acme-v02.api.letsencrypt.org/directory
        # Email address used for ACME registration
        email: arkadiusz.k.e@gmail.com
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
            name: letsencrypt
        # Enable the DNS-01 challenge provider
        solvers:
            -   http01:
                    ingress:
                        class: nginx
            -   dns01:
                    digitalocean:
                        tokenSecretRef:
                            name: digitalocean-dns
                            key: access-token
