name: Docker images

on:
  workflow_dispatch: ~

env:
  REGISTRY: ghcr.io
  PHP_IMAGE_NAME: arminek/thumbnail-generator-php
  CADDY_IMAGE_NAME: arminek/thumbnail-generator-caddy

jobs:
  app:
    runs-on: ubuntu-20.04
    name: "Run app tests"
    steps:
      - uses: actions/checkout@v2
      - name: App tests
        run: make test-run

  build-and-publish-image-php:
    runs-on: ubuntu-20.04
    name: "Build & publish php docker image"
    timeout-minutes: 10
    needs: [ "app" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.PHP_IMAGE_NAME }}
          tags: |-
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          target: symfony_php
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-publish-image-caddy:
    runs-on: ubuntu-20.04
    name: "Build & publish caddy docker image"
    timeout-minutes: 10
    needs: [ "app" ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.CADDY_IMAGE_NAME }}
          tags: |-
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          target: symfony_caddy
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
